#!/bin/env bash

User1='e3c593be-343f-49a5-9d35-d602d5d57316'
User2='d1c3bd04-88d1-443f-bf5f-e6ff04d1e8d1'

# SessionId=`http POST http://localhost:5018/auth username="samin" password="1234" --headers | sed -n -e 's/X-Session-Id: //p'`
SessionId=$User1
http --ignore-stdin --form POST http://localhost:5018/post X-Session-Id:$SessionId images@test.jpg images@test.jpg creatorid=11 caption='hi guys look at this picture I took!!'

SessionId=$User2
http --ignore-stdin --form POST http://localhost:5018/post X-Session-Id:$SessionId images@test.jpg images@test2.png creatorid=4 caption='no check my one out'

SessionId=$User2
http --ignore-stdin POST http://localhost:5018/comment X-Session-Id:$SessionId creatorid=4 postid=1 content='this picture is ugly'

SessionId=$User1
http --ignore-stdin POST http://localhost:5018/comment X-Session-Id:$SessionId creatorid=11 postid=1 content='we took the same picture'

SessionId=$User2
http --ignore-stdin POST http://localhost:5018/comment X-Session-Id:$SessionId creatorid=4 postid=1 content='fine I just hate you'

SessionId=$User1
http --ignore-stdin POST http://localhost:5018/comment X-Session-Id:$SessionId creatorid=11 postid=2 content='I hate you too'
